version: '3'
services: 
  component:
    # for building from source
    image: heipa/qanary-component-nllb:thesis
    build: 
      context: .
      dockerfile: Dockerfile
    network_mode: host
    env_file:
      - .env
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface/
